# ОГРАНИЧЕНИЕ В 25 ЭЛЕМЕНТОВ НА КАЖДЫЙ СПИСОК!
lst1 = {
        "🛰 Corvax - Мейн 🚀": "https://game2.station14.ru/main/server/status",
        "🛰 Corvax - Элизиум 🌑": "https://game1.station14.ru/elysium/server/status",
        "🛰 Corvax - Небула ✨": "https://game1.station14.ru/nebula/server/status",
        "🛰 Corvax - Атара 🌀": "https://game1.station14.ru/athara/server/status",
        "🛰 Corvax - Солярис 🌕": "https://game2.station14.ru/solaris/server/status",
        "🛰 Corvax - Эхо ☄": "https://game2.station14.ru/echo/server/status",
        "🛰 Corvax - Нова 🪐": "https://game1.station14.ru/nova/server/status",
        "🛰 Corvax - Ждалкер ☢": "https://game.stalkers14.xyz/status",
        "🛰 Corvax - Колониальные Морпехи 🌎": "https://game1.station14.ru/marines-main/server/status",
        "🛰 Corvax - 🚽 ОТКРЫТИЕ СКИБИДИ СТАНЦИИ 🚽": "лол ебать ахахахахах",
        "🦅 Imperial Space - Кассиопея 🔮": "http://193.164.16.220:1212/status",
        "🦅 Imperial Space - Эридан 🦄": "http://193.164.16.220:1213/status",
        "🦅 Imperial Space - Цефей 👑": "http://193.164.16.220:1214/status",
        "🦅 Imperial Space - Пиксис 🧭": "http://193.164.17.94:1212/status",
        "🦅 Imperial Space - Форнакс 🔥": "http://193.164.17.94:1213/status",
        "🦅 Imperial Space - Октансис 🔭": "http://193.164.17.94:1214/status",
        "✅ SS220 - Стрелец": "http://141.95.102.4:1214/status",
        "✅ SS220 - Орион": "http://141.95.102.4:1212/status",
        "✅ SS220 - Персей": "http://141.95.102.4:1213/status",
        "😈 Cerberus Space": "http://194.93.2.178:1212/status",
        "🦊 Lost Paradise [HARAM 18+]": "http://193.164.17.48:1212/status",
        "🌆 Project Backmen": "http://46.72.238.71:1212/status",
        "🦽 SUNRISE - Феникс": "https://sunrise14.top/fenix/status",
        "🦽 SUNRISE - Ореол": "https://sunrise14.top/oreol/status",
        "🦽 SUNRISE - Фронтир": "https://sunrise14.top/tether/status",
    }

lst2 = {
    "⚪ White Dream - Атараксия 🌀": "https://ludere.ss14.su/ataraxia/status",
    "⚪ White Dream - Амур 👠 [HARAM 18+]": "https://ludere.ss14.su/amour/status",
    "⚪ White Dream - Мейд ☄️": "https://ludere.ss14.su/maid/status",
    "⚪ White Dream - Грид 🩸": "https://ludere.ss14.su/grid/status",
    "⚪ WD & Phoenix - Колониальные Морпехи 🌍": "https://ludere.ss14.su/marines/status",
    "📚 Space Stories - Universe 👨🏻‍🚀": "http://spacestories.club:1212/status",
    "📚 Space Stories - Atlas 🗺": "http://spacestories.club:1214/status",
    "📚 Space Stories - Колониальные Морпехи 🌍": "http://spacestories.club:1213/status",
    "👽 Мёртвый Космос - Фобос": "http://f1.deadspace14.net:1212/status",
    "👽 Мёртвый Космос - Титан": "http://f2.deadspace14.net:1212/status",
    "👽 Мёртвый Космос - Союз-1": "http://f2.deadspace14.net:1213/status",
    "👽 Мёртвый Космос - Деймос": "http://f3.deadspace14.net:1213/status",
    "👽 Мёртвый Космос - Фронтир": "http://ff.deadspace14.net:1213/status",
    "👽 Мёртвый Космос - Колониальные Морпехи 🌍": "http://ff2.deadspace14.net:1214/status",
    "🧙🏻‍♂️ Шиздены - Lizard": "https://lizard.spacestation14.io/server/status",
    "🧙🏻‍♂️ Шиздены - Miros": "https://miros.spacestation14.io/server/status",
    "🧙🏻‍♂️ Шиздены - Salamander": "https://lizard.spacestation14.io/salamander/status",
    "🧙🏻‍♂️ Шиздены - Leviathan": "https://leviathan.spacestation14.com/server/status",
    "🧙🏻‍♂️ Шиздены - Vulture": "http://leviathan.spacestation14.com/vulture/status",
    "[EN] Rouny's Marine Corps Alamo (Морпехи) 🌍": "https://alamo.rouny-ss14.com/status",
}